export const DATA = [
  {
    id: 1,
    name: 'Aarav Mehta',
    email: 'aarav.mehta@example.com',
    company: 'TechVision',
    engaged: true,
    lastContacted: '2025-03-10',
    stage: 1,
  },
  {
    id: 2,
    name: 'Priya Sharma',
    email: 'priya.sharma@example.com',
    company: 'InnovateX',
    engaged: false,
    lastContacted: '',
    stage: 2,
  },
  {
    id: 3,
    name: 'Rahul Verma',
    email: 'rahul.verma@example.com',
    company: 'FutureSoft',
    engaged: true,
    lastContacted: null,
    stage: 3,
  },
  {
    id: 4,
    name: 'Sneha Kapoor',
    email: 'sneha.kapoor@example.com',
    company: 'CodeCrafters',
    engaged: false,
    lastContacted: '2025-03-05',
    stage: 1,
  },
  {
    id: 5,
    name: 'Arjun Nair',
    email: 'arjun.nair@example.com',
    company: 'ByteWorks',
    engaged: true,
    lastContacted: '2025-03-11',
    stage: 2,
  },
  {
    id: 6,
    name: 'Neha Raj',
    email: 'neha.raj@example.com',
    company: 'SoftLab',
    engaged: true,
    lastContacted: '2025-03-09',
    stage: 3,
  },
  {
    id: 7,
    name: 'Kunal Bhatia',
    email: 'kunal.bhatia@example.com',
    company: 'NextGenAI',
    engaged: false,
    lastContacted: '2025-03-06',
    stage: 1,
  },
  {
    id: 8,
    name: 'Meera Iyer',
    email: 'meera.iyer@example.com',
    company: 'AIHub',
    engaged: true,
    lastContacted: '2025-03-07',
    stage: 2,
  },
  {
    id: 9,
    name: 'Ravi Desai',
    email: 'ravi.desai@example.com',
    company: 'DeepThink',
    engaged: false,
    lastContacted: '2025-03-04',
    stage: 3,
  },
  {
    id: 10,
    name: 'Tanvi Malhotra',
    email: 'tanvi.malhotra@example.com',
    company: 'SmartWare',
    engaged: true,
    lastContacted: '2025-03-13',
    stage: 1,
  },
  {
    id: 11,
    name: 'Vikram Sinha',
    email: 'vikram.sinha@example.com',
    company: 'CyberSync',
    engaged: false,
    lastContacted: '2025-03-02',
    stage: 2,
  },
  {
    id: 12,
    name: 'Sanya Khurana',
    email: 'sanya.khurana@example.com',
    company: 'AIForge',
    engaged: true,
    lastContacted: '2025-03-01',
    stage: 3,
  },
  {
    id: 13,
    name: 'Amit Saxena',
    email: 'amit.saxena@example.com',
    company: 'CodeMinds',
    engaged: false,
    lastContacted: '2025-03-03',
    stage: 1,
  },
  {
    id: 14,
    name: 'Pooja Agrawal',
    email: 'pooja.agrawal@example.com',
    company: 'NeuralTech',
    engaged: true,
    lastContacted: '2025-03-15',
    stage: 2,
  },
  {
    id: 15,
    name: 'Saurabh Choudhary',
    email: 'saurabh.choudhary@example.com',
    company: 'DataDriven',
    engaged: false,
    lastContacted: '2025-03-14',
    stage: 3,
  },
  {
    id: 16,
    name: 'Sarthak Naik ',
    email: 'Sarthak.naik@example.com',
    company: 'DataDriven',
    engaged: true,
    lastContacted: '2025-03-14',
    stage: 3,
  },
  {
    id: 17,
    name: 'Deepak Choudhary',
    email: 'deepak.choudhary@example.com',
    company: 'Artisian',
    engaged: false,
    lastContacted: '2025-03-14',
    stage: 1,
  },
  {
    id: 18,
    name: 'Saurabh Gupta',
    email: 'saurabh.choudhary@example.com',
    company: 'DataDriven',
    engaged: false,
    lastContacted: '2025-03-14',
    stage: 4,
  },
  {
    id: 19,
    name: 'Hitesh Choudhary',
    email: 'hitesh.choudhary@example.com',
    company: 'DataDriven',
    engaged: false,
    lastContacted: '2025-03-14',
    stage: 3,
  },
  {
    id: 20,
    name: 'Shubham Gaur',
    email: 'saurabh.choudhary@example.com',
    company: 'Sales force',
    engaged: false,
    lastContacted: '2025-03-14',
    stage: 4,
  },
  {
    id: 21,
    name: 'Ashutosh Rao',
    email: 'rao.ashutosh@example.com',
    company: 'Make My trip',
    engaged: false,
    lastContacted: '2025-03-12',
    stage: 4,
  },
]
